echo "Setting up rana's git aliases"
# Aliases I use for git
alias gb='git branch -a -v'
alias gs='git status'
alias gd='git diff'
alias ga='git add'
alias gc='git commit'
alias gb='git branch'
alias gco='git checkout'
alias pull='git pull'
alias push='git push'
alias commit='git commit'
alias branch='git branch'
alias add='git add'
alias diff='git diff'
alias status='git status'
